// Generated by scripts/sync-ocr-assets.mjs. Do not edit.
//
// The onnxruntime build under public/ocr/wasm/<version>/. The version is
// in the path because the runtime's own filename never changes, which is
// what makes it safe to cache the file forever.
export const ORT_RUNTIME_VERSION = "1.27.0";
